### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by porkie02** [DetectiveSquirrel/Aim-Bot#2]
Hi whenever I use this plugin it errors out with this.

Method error: Render : System.NullReferenceException: Object reference not set to an instance of an object.
   at PoeHUD.Poe.RemoteMemoryObjects.Camera.WorldToScreen(Vector3 vec3, EntityWrapper entityWrapper)
   at Aimbot.Core.Main.DrawEllipseToWorld(Vector3 vector3Pos, Int32 radius, Int32 points, Int32 lineWidth, Color color)
   at Aimbot.Core.Main.Render()
   at PoeHUD.Plugins.BasePlugin._Render()

**Comment by porkie02** [comment]
Nevermind, I updated to latest git version of poehub and it seems to be fixed.
